services:
  db:
    image: mariadb:10.11
    container_name: license_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: bonus2548
      MARIADB_DATABASE: License
      MARIADB_USER: nutx
      MARIADB_PASSWORD: bonus2548
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u nutx --password=$$MARIADB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  server:
    build:
      context: ./Server
    container_name: license_api
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_ENV: production
      PORT: 3000
      CLIENT_ORIGIN: http://157.254.192.134
      JWT_SECRET: Secret_Ready_Manager
      DATABASE_URL: mysql://nutx:bonus2548@db:3306/License
      DB_HOST: db
      DB_USER: nutx
      DB_PASSWORD: bonus2548
      DB_NAME: License
      BOT_SECRET: READY_MANAGER_BOT_SECRET_2026
      EASYSLIP_API_KEY: 50eb9b32-31c3-48ae-a6e2-fee943a30515
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    networks:
      - app_network

  bot:
    build:
      context: ./Bot
    container_name: license_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      EASYSLIP_API_KEY: 50eb9b32-31c3-48ae-a6e2-fee943a30515
    depends_on:
      - server
    networks:
      - app_network

  client:
    build:
      context: ./Client
    container_name: license_web
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge